Repository meiliyuri/AI-Study-Planner-Group8, pull requests merged in 2025-09, with the labels that each got.

#18 fix: keep unit cards in single-line flex layout after search reset
  app/static/css/style.css
  app/static/js/app.js
Labels: bug, enhancement

#25 Update the pull code step in README
  README.md
Labels: documentation

#30 Add a chat function to the AI Debug Log for re-generating plans
  app/static/js/app.js
  app/templates/index.html
Labels: enhancement

#52 Plan Validation: show prerequisites, classify availability errors, and improve error/warning display
  app/controller.py
  app/static/js/app.js
  data_loader.py
Labels: enhancement
